server:
  port: ${PORT:8181}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0



logging:
  level:
    org:
      hibernate:
        SQL: debug

spring:
  datasource:
    username : postgres
    password : sumi123
    url : jdbc:postgresql://localhost:5432/SList
  h2: 
    console:
      enabled : true
    
  jpa:
      database-platform : org.hibernate.dialect.PostgreSQLDialect

   